MODULE StockAccounting;

REQUIRE Item, LegalEntity, Statement, Receipt, StockItem, Customer;

NAVIGATOR {
    NEW FOLDER masterData 'Справочники' FIRST WINDOW toolbar {
        NEW items;
        NEW legalEntities;
        NEW auto;
        NEW customers;
    }
    NEW FOLDER documents 'Документы' AFTER masterData WINDOW toolbar {
        NEW receipts;
        NEW statements;
    }
    NEW currentBalanceItemStock AFTER documents;
}

